name: curiosity
favicon: null
layout_spectrum: 0.3748881856445223
typography_spectrum: 0.05101309600286186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8158258653711528
  lightness: 0.0891877431422472
  saturation: 0.27728083613328636
  rhythmicContrast: 0.1567728277295828
purpose: []
